name: publish-package

# on:
#   push:
#     tags:
#       - "v*"
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure .npmrc
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Prerequisite installation
        run: |
          npm ci
          cd lib/constructs/lambda/functions; npm ci
      # - name: Check formatting and build from source
      #   run: |
      #     npm run format:check
      #     npm run lint:check
      #     npm run build
      # - name: Publish
      #   run: |
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}